name: MXRT demo app repo CI/CD

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    
    - name: Make scripts executable
      run: |
        chmod +x ./.github/scripts/install-dependencies.sh
        chmod +x ./.github/scripts/docker-build.sh

    - name: Install dependencies
      run: ./.github/scripts/install-dependencies.sh

    - name: test
      run: |
        echo pip --version
        echo java --version
