name: MXRT demo app repo CI/CD

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    
    - name: Make scripts executable
      run: |
        chmod +x ./.github/scripts/install-dependencies.sh
        chmod +x ./.github/scripts/build.sh
        chmod +x ./.github/scripts/docker-build.sh
        chmod +x ./.github/scripts/docker-push.sh

    - name: Install dependencies
      run: ./.github/scripts/install-dependencies.sh

    - name: build apps
      run: ./.github/scripts/build.sh

    - name: test
      run: echo test cases not available

    - name: Build docker image
      if: github.ref == 'refs/heads/develop'
      run: ./.github/scripts/docker-build.sh

    - name: Build docker push
      if: github.ref == 'refs/heads/develop'
      run: echo docker push not completed
      #run: ./.github/scripts/docker-push.sh manishyadav153@gmail.com ${{ secrets.DOCKER_PAT }} latest

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    - name: Docker image pull
      if: github.ref == 'refs/heads/develop'
      run: echo Not started
